# Generated by Django 3.2.9 on 2021-11-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_full_name',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
    ]
